language: java
jdk:
  - oraclejdk8
sudo: false

directories:
  -&TEST
  -&MAIN

#before_install:
#  - pip install --user codecov



script:
  - gradle clean
  - gradle test
  - gradle -i clean jacocoTestReport

#after_script:
#  - gradle jacocoTestReport

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
